sudo: required
services:
  - docker

before_install:
  - docker build -t mybr0d0cker/docker-react2 -f Dockerfile.dev .

#script:
#  - docker run -e CI=true USERNAME/docker-react npm run test

script:
  - docker run -e CI=true mybr0d0cker/docker-react2 npm run test -- --coverage

deploy:
  provider: elastikbeanstalk
  region: "us-east-1" 
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-001380156346"
  bucket_path:"docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"